### PR TITLE
Remove all navigation-related reference.

### PR DESCRIPTION
**Pull request by ahtsan**
This repository should be a pure world repository and not having any navigation related code.

* Remove all navigation launch files
* Remove all navigation dependencies

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mm318** [comment]
Looks good!

I guess this change needs to be merged "atomically" with https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch/pull/135.

**Review by ojasjoshi — COMMENTED** [review]
Looks good.. are we missing to add `small_house_turtlebot_slam.launch` in the sample app? (although it might not make sense in the sample app either)

**Comment by ahtsan** [comment]
> Looks good.. are we missing to add `small_house_turtlebot_slam.launch` in the sample app? (although it might not make sense in the sample app either)

Yes, I discussed with Miaofei and we both think the slam launch file shouldn’t be here, so we might just as well remove it.

**Comment by mm318** [comment]
> Looks good.. are we missing to add `small_house_turtlebot_slam.launch` in the sample app? (although it might not make sense in the sample app either)

I don't think the `*_slam.launch` file is used by any sample app (or anything, really). Right?

**Review by mm318 — APPROVED** [review]

**Pull request merged**
