### PR TITLE
Fix SDF models path

### PR DESCRIPTION
**Pull request by piraka9011**
*Issue #, if available:*

N/A

*Description of changes:*

Change the SDF models path by removing the `models` directory.
This makes the SDF compatible with Gazebo and GZWeb.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

These changes were performed by running:

```
find . \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i 's/models\/aws/aws/'
find . \( -type d -name .git -prune \) -o -type f -exec dos2unix {} \;
```

And pretty printing all the XML in the DAE files:

```
def xml_to_pretty_xml(input_file_name):
    doc = minidom.parse(input_file_name)
    xmlstr = doc.toprettyxml(encoding="utf-8")
    temp_file_name = input_file_name + "_temp"
    old_file_name = input_file_name + "_old"
    with open(temp_file_name, "w") as f:       
        f.write(xmlstr.decode('utf-8'))
    os.rename(input_file_name, old_file_name)
    os.rename(temp_file_name, input_file_name)
    os.remove(old_file_name)
```

Tested locally on Ubuntu 18.04 and in RoboMaker on ROS Melodic.

Signed-off-by: Anas Abou Allaban <aabouallaban@pm.me>

### CODE REVIEW

**Comment by samuelgundry** [comment]
Thanks for this.  Unfortunately, we don't have CI setup.  For testing in RoboMaker, did you use a sample application such as Person Detection? Or did you just load this world w/o downstream dependencies?  Can you also please test in Kinetic/Gazebo 7?

**Comment by piraka9011** [comment]
Just followed the instructions in the README. (`rosdep install`, `colcon build`, `roslaunch...`)
I bundled and launched a simulation application w/o a robot application.

**Comment by piraka9011** [comment]
I just tested this on Gazebo 7, Kinetic and verified no errors in the CloudWatch logs as well.

**Comment by samuelgundry** [comment]
Thanks for testing K/7.

**Review by samuelgundry — APPROVED** [review]

**Comment by samuelgundry** [comment]
@piraka9011  did you test directly in Gazebo or only via ROS?   See https://github.com/aws-robotics/aws-robomaker-small-house-world/issues/21

**Comment by piraka9011** [comment]
Only via ROS using `roslaunch aws_robomaker_small_house_world view_small_house.launch`.

**Comment by mm318** [comment]
Hi @piraka9011, was this pull request for adding compatibility with GZWeb? I would assume this repository was already compatible with Gazebo.

**Comment by piraka9011** [comment]
Yes, however, there were some issues with GZWeb in terms of the format of the DAE files and the URI to the meshes.
It seems that GZWeb parses the model URIs differently than Gazebo (and for some reason this works with `roslaunch` but not Gazebo standalone?)

I didn't dig too much into this though.

**Pull request merged**
