### PR TITLE
Ros2 devel

### PR DESCRIPTION
**Pull request by swatifulzele**
*Issue #, if available:*

*Description of changes:*
1. Migrated CMakeLists.txt and package.xml from ros1 to ros2.
2. Modified paths in sdf files for all models in small house.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mm318** [comment]
When I do `rosdep install --from-paths . --ignore-src -r -y`, I am getting the following error:
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
aws_robomaker_small_house_world: Cannot locate rosdep definition for [dwa_local_planner]
```
Is this expected? Or has the usage of the package changed?

**Comment by mm318** [comment]
The `gazebo worlds/small_house.world` usage is working.

@swatifulzele Will you be porting over the launch file usage to ROS2 as well?

**Comment by swatifulzele** [comment]
> usage

Removed "dwa_local_planner and moveit_ros" from the package.xml as it is not been used by the aws-robomaker-small-house-world.

**Comment by swatifulzele** [comment]
> When I do `rosdep install --from-paths . --ignore-src -r -y`, I am getting the following error:
> 
> ```
> ERROR: the following packages/stacks could not have their rosdep keys resolved
> to system dependencies:
> aws_robomaker_small_house_world: Cannot locate rosdep definition for [dwa_local_planner]
> ```
> 
> Is this expected? Or has the usage of the package changed?

Removed "dwa_local_planner and moveit_ros" from the package.xml as it is not been used by the aws-robomaker-small-house-world.

**Comment by swatifulzele** [comment]
> The `gazebo worlds/small_house.world` usage is working.
> 
> @swatifulzele Will you be porting over the launch file usage to ROS2 as well?

Yes, the launch files being used by aws-robomaker-sample-application-persondetection is already ported i.e "small_house.launch and small_house_turtlebot_navigation.launch".
Once the current PR is merged, I will raise next PR with ported launch files.

**Review by mm318 — APPROVED** [review]

**Pull request merged**
